---
- name: docker | install prerequisite packages
  yum:
    name: "{{ item  }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper
    - lvm2

- name: docker | extend yum timeout
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: '^timeout'
    line: 'timeout=300'

- name: docker | add docker-ce repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: docker | set docker-ce repo
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0755

- name: docker | install docker-ce
  yum: 
    name: docker-ce
    state: present

- name: docker | restart docker
  systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: docker | test docker command
  shell: "docker --version"
  register: return_from_shell

- name: docker | show command result
  debug:
    var: return_from_shell

- name: docker | configure net.ipv4.ip_forward = 1
  lineinfile:
    dest: /etc/sysctl.conf
    state: present
    regexp: '^net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward=1'
